title: CPAN-SEC
author: CPAN Security Outreach & Information Project
#email: cpan-security@perl.org
description: >-
  CPAN Security Working Group (CPAN-SEC)
baseurl: ""
url: "https://security.metacpan.org"
domain: security.cpan.org

header_pages:
  - /docs/report
  - /docs/pre-release-disclosure
  - /docs/charter
  - /presentations/
  - /docs/minutes/
  - /docs/readinglist

# Build settings
theme: minima

minima:
  skin: auto

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
